FROM docker.grammatech.com:14850/synthesis/cl

RUN apt-get -y update && \
    apt-get -y install man-db graphviz texinfo pandoc pkg-config libffi-dev

ENV PATH=/gt/sel/bin:$PATH \
    GT_DOCKER_CHOWN_PATHS=""

COPY . /gt/sel

RUN cd /gt/sel && make

WORKDIR /gt/sel

CMD /bin/bash
