variables:
  DOCKER_REGISTRY: "docker.grammatech.com:14850"
  LOCAL_IMAGE_NAME: '$CI_BUILD_REF_NAME-$CI_PIPELINE_ID'

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY

stages:
  - build
  - test-and-tag
  - deploy
  - dependents

.build-template: &build
  script:
    - if [ "$OS" = "ubuntu" ];
      then
          docker pull $DOCKER_REGISTRY/synthesis/cl:latest;
      else
          docker pull $DOCKER_REGISTRY/synthesis/cl:$OS;
      fi

    - cp .ci/Dockerfile.$OS Dockerfile
    - docker build -f Dockerfile -t ${LOCAL_IMAGE_NAME}-${OS} .

build:
  stage: build
  variables:
    OS: 'ubuntu'
  <<: *build

build-arch:
  stage: build
  variables:
    OS: 'arch'
  <<: *build

.run-template: &run
  script:
    # If on master branch, push test results to DataManager and push
    # up a new "latest" image, otherwise, run locally.
    - if [ "$CI_BUILD_REF_NAME" = "master" ];
      then
          if [ "$OS" = "ubuntu" ];
          then
              docker run -e LOCAL_USER=root -e GT=yes ${LOCAL_IMAGE_NAME}-${OS} /bin/bash -c "cd /gt/sel && make check-testbot";
              docker tag ${LOCAL_IMAGE_NAME}-${OS} $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest;
              docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest;
          elif [ "$OS" = "arch" ];
          then
              docker run -e LOCAL_USER=root -e GT=yes ${LOCAL_IMAGE_NAME}-${OS} /bin/bash -c "cd /gt/sel && make check-testbot";
              docker tag ${LOCAL_IMAGE_NAME}-${OS} $DOCKER_REGISTRY/$CI_PROJECT_PATH:arch;
              docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:arch;
          else
              docker run -e LOCAL_USER=root -e GT=yes ${LOCAL_IMAGE_NAME}-${OS} /bin/bash -c "cd /gt/sel && make check";
          fi
      else
          docker run -e LOCAL_USER=root -e GT=yes ${LOCAL_IMAGE_NAME}-${OS} /bin/bash -c "cd /gt/sel && make check";
      fi

    # Cleanup local image.
    - docker rmi -f ${LOCAL_IMAGE_NAME}-${OS}

run:
  stage: test-and-tag
  variables:
    OS: 'ubuntu'
  <<: *run

run-arch:
  stage: test-and-tag
  variables:
    OS: 'arch'
  <<: *run

trigger_bed:
  stage: dependents
  script:
    - "curl -X POST -F token=53072adf26824b62fe4bd75f81a816 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/209/trigger/pipeline"
  only:
    - master

trigger_bug-injector:
  stage: dependents
  script:
    - "curl -X POST -F token=eb76bc2f8009af7005b43bf8f63bb0 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/347/trigger/pipeline"
  only:
    - master

trigger_evo-rings:
  stage: dependents
  script:
    - "curl -X POST -F token=3927540b9948e9eb8d3b1774dd9627 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/80/trigger/pipeline"
  only:
    - master

pages:
  stage: deploy
  script:
    - docker run -e LOCAL_USER=root ${LOCAL_IMAGE_NAME}-arch /bin/bash -c "mkdir -p /public && cd /gt/sel && make doc && cp -R doc/software-evolution-library/* /public/"
    - docker cp $(docker ps -alq):/public ./
  artifacts:
    paths:
      - public
  only:
    - master
