variables:
  DOCKER_REGISTRY: "docker.grammatech.com"
  LOCAL_IMAGE_NAME: '$CI_PROJECT_PATH-$CI_BUILD_REF_NAME-$CI_PIPELINE_ID'

before_script:
  - docker info

stages:
  - build
  - check-format
  - test-and-tag
  - dependents
  - deploy
  - cleanup

check-format:
  stage: check-format
  script:
    - export FROM=$DOCKER_REGISTRY/synthesis/sel/arch-sbcl:${CI_BUILD_REF_NAME}
    - docker pull $FROM;
    - docker build --rm --build-arg=FROM=$FROM -f .ci/Dockerfile.formatter .;
  allow_failure: true

.build-template: &build
  script:
    - if [ "$OS" = "ubuntu" ];
      then
          export PULL_TAG=latest;
      else
          export PULL_TAG=${OS};
      fi
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    - docker pull $DOCKER_REGISTRY/synthesis/clang/${OS}
    - docker pull $DOCKER_REGISTRY/synthesis/java-mutator:${PULL_TAG}
    - docker pull $DOCKER_REGISTRY/synthesis/cl:${PULL_TAG}
    - docker build --build-arg=GT=yes  --build-arg=LISP=${LISP} -f .ci/Dockerfile.${OS} -t ${LOCAL_IMAGE_NAME}-${OS}-${LISP} .
    - if [ ! "$CI_BUILD_REF_NAME" = "latest" ];
      then
          docker tag ${LOCAL_IMAGE_NAME}-${OS}-${LISP} $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS}-${LISP}:${CI_BUILD_REF_NAME};
          docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY;
          docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS}-${LISP}:${CI_BUILD_REF_NAME};
      fi

build-ubuntu-ccl:
  stage: build
  variables:
    OS: 'ubuntu'
    LISP: 'ccl'
  <<: *build

build-ubuntu-sbcl:
  stage: build
  variables:
    OS: 'ubuntu'
    LISP: 'sbcl'
  <<: *build

build-arch-ccl:
  stage: build
  variables:
    OS: 'arch'
    LISP: 'ccl'
  <<: *build

build-arch-sbcl:
  stage: build
  variables:
    OS: 'arch'
    LISP: 'sbcl'
  <<: *build

.run-template: &run
  script:
    # If on master branch, push test results to DataManager and push
    # up a new "latest" image, otherwise, run locally.
    - if [ "$CI_BUILD_REF_NAME" = "master" ];
      then
          docker run -e LOCAL_USER=root -e GT=yes -e REPORT=yes -e LISP=${LISP} ${LOCAL_IMAGE_NAME}-${OS}-${LISP} /bin/bash -c "cd /root/quicklisp/local-projects/sel && unbuffer make check";
          if [ "$LISP" = "sbcl" ];
          then
              docker tag ${LOCAL_IMAGE_NAME}-${OS}-${LISP} $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS};
              docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY;
              docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS};
          fi
      else
          docker run -e LOCAL_USER=root -e GT=yes -e LISP=${LISP} ${LOCAL_IMAGE_NAME}-${OS}-${LISP} /bin/bash -c "cd /root/quicklisp/local-projects/sel && unbuffer make check";
      fi

run-ubuntu-ccl:
  stage: test-and-tag
  variables:
    OS: 'ubuntu'
    LISP: 'ccl'
  <<: *run

run-ubuntu-sbcl:
  stage: test-and-tag
  variables:
    OS: 'ubuntu'
    LISP: 'sbcl'
  <<: *run

run-arch-ccl:
  stage: test-and-tag
  variables:
    OS: 'arch'
    LISP: 'ccl'
  <<: *run

run-arch-sbcl:
  stage: test-and-tag
  variables:
    OS: 'arch'
    LISP: 'sbcl'
  <<: *run

trigger_bed:
  stage: dependents
  script:
    - "curl -X POST -F token=53072adf26824b62fe4bd75f81a816 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/209/trigger/pipeline"
  only:
    - master

trigger_evo-rings:
  stage: dependents
  script:
    - "curl -X POST -F token=3927540b9948e9eb8d3b1774dd9627 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/80/trigger/pipeline"
  only:
    - master

trigger_genpatcher:
  stage: dependents
  script:
    - "curl -X POST -F token=86d8095830c9823728e4204584dc16 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/943/trigger/pipeline"
  only:
    - master

trigger_refactoring-mutations:
  stage: dependents
  script:
    - "curl -X POST -F token=5ad3804083cbeb694cea4c126029e8 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/1271/trigger/pipeline"
  only:
    - master

trigger_resolve:
  stage: dependents
  script:
    - "curl -X POST -F token=943ae481fed1a7ea21d7439bf3a8f3 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/881/trigger/pipeline"
  only:
    - master

trigger_ssr:
  stage: dependents
  script:
    - "curl -X POST -F token=c83ba713bf7f104805a160a169f586 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/787/trigger/pipeline"
  only:
    - master

trigger_variegate:
  stage: dependents
  script:
    - "curl -X POST -F token=759ed12ac12d057eee4118b3fe6214 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/928/trigger/pipeline"
  only:
    - master

pages:
  stage: deploy
  script:
    - export CONTAINER_FILE=${LOCAL_IMAGE_NAME}-arch-sbcl.container
    - mkdir -p $(dirname ${CONTAINER_FILE})
    - docker run -e LOCAL_USER=root -e GT=yes --cidfile=${CONTAINER_FILE} ${LOCAL_IMAGE_NAME}-arch-sbcl /bin/bash -c "mkdir -p /public && cd /root/quicklisp/local-projects/sel && make doc && cp -R doc/software-evolution-library/* /public/"
    - docker cp $(cat ${CONTAINER_FILE}):/public ./
  artifacts:
    paths:
      - public
  only:
    - master

cleanup:
  stage: cleanup
  script:
    - date
  after_script:
    - docker rmi -f ${LOCAL_IMAGE_NAME}-arch-ccl
    - docker rmi -f ${LOCAL_IMAGE_NAME}-arch-sbcl
    - docker rmi -f ${LOCAL_IMAGE_NAME}-ubuntu-sbcl
    - docker rmi -f ${LOCAL_IMAGE_NAME}-ubuntu-ccl
  when: always
