;;; Cons-cell Genomes
(defmethod inds ((genome cons))
  (unless (null genome)
    (flet ((follow (dir list)
             (mapcar (lambda (el) (cons dir el))
                     (if (consp list) (inds list) '(())))))
      (append '(()) (follow :a (car genome)) (follow :d (cdr genome))))))

(defmethod ind ((genome list) index)
  (flet ((get-at (list dir) (case dir (:a (car list)) (:d (cdr list)))))
    (if (cdr index)
        (ind (get-at genome (car index)) (cdr index))
        (get-at genome (car index)))))

(defmethod (setf ind) (new (genome list) index)
  (if (cdr index)
      (setf (ind (case (car index)
                   (:a (car genome))
                   (:d (cdr genome)))
                 (cdr index))
            new)
      (case (car index)
        (:a (rplaca genome new) new)
        (:d (rplacd genome (if (and (proper-list-p genome) new)
                               (cons new nil)
                               new)) new))))

(defun del-ind (genome index)
  (if (cddr index)
      (del-ind (case (car index) (:a (car genome)) (:d (cdr genome)))
               (cdr index))
      (case (car index)
        (:a (if (cdr index)
                (rplaca genome
                        (case (cadr index)
                          (:a (cdar genome))
                          (:d (caar genome))))
                (progn (rplaca genome (cadr genome))
                       (rplacd genome (cddr genome)))))
        (:d (rplacd genome
                    (case (cadr index)
                      (:a (cddr genome))
                      (:d (cadr genome))))))))


;;; Cons-cell Methods
(defmethod copy ((genome list) &key edits fitness)
  (copy-tree genome))

(defmethod size ((genome list))
  (if (consp genome)
      (+ (size (car genome)) (size (cdr genome)))
      1))

(defmethod genome-average-keys ((genome list) place)
  (let ((inds (list (butlast place) place
                    (append place '(:a)) (append place '(:d)))))
    (dolist (key *genome-averaging-keys*)
      (let ((new (/ (apply #'+ (mapcar (lambda (el)
                                         (or (cdr (assoc key (ind genome el)))
                                             0))
                                       inds))
                    4)))
        (if (assoc key (ind genome place))
            (setf (cdr (assoc key (ind genome place))) new)
            (push (cons key new) (ind genome place)))))
    genome))

(defmethod edit-distance ((a list) (b list))
  (error "No edit distance metric implemented for cons trees."))

(defun ensure-proper-list (lisp)
  (unless (proper-list-p lisp) (setf (cdr lisp) (cons (cdr lisp) nil)))
  lisp)

(defmethod insert ((genome list) &key (good-key nil) (bad-key nil))
  (declare (ignorable bad-key))
  (let ((dup (location genome good-key))
        (ins (location genome good-key))
        (new (copy-tree genome)))
    (setf (ind new ins)
          (cons (copy-tree (ind genome ins))
                (copy-tree (ind genome dup))))
    (values (ensure-proper-list new) (list ins dup))))

(defmethod cut ((genome list) &key (good-key nil) (bad-key nil))
  (declare (ignorable good-key))
  (let ((del (location genome bad-key))
        (new (copy-tree genome)))
    (del-ind new del)
    (values (ensure-proper-list new) del)))

(defmethod swap ((genome list) &key (good-key nil) (bad-key nil))
  (let* ((a (location genome good-key))
         (b (location genome bad-key))
         (ordered (sort (list a b) #'< :key #'length))
         (new (copy-tree genome)))
    (setf (ind new (second ordered)) (copy-tree (ind genome (first ordered))))
    (setf (ind new (first ordered))  (copy-tree (ind genome (second ordered))))
    (values (ensure-proper-list new) ordered)))

(defmethod crossover ((a list) (b list))
  (let* ((inds-a (inds a))
         (inds-b (inds b))
         (points-in-common (remove-if-not (lambda (it) (member it inds-a)) inds-b))
         (point (random-elt points-in-common))
         (new (copy-tree a)))
    (setf (ind new point) (ind b point))
    (values (ensure-proper-list new) point)))
