#!/bin/bash
# SEL=/pdietz/quicklisp/local-projects/sel
if [ ""$SEL = "" ]; then
    echo Set SEL to sel directory
    exit 1
fi
for d in `cat all-llvm-cpp`; do
    # These cause too many alarms
    # Eventually remove define, include from pattern
    grep -E "__asm|define|include|__attribute__" $d > /dev/null
    if [ $? = 1 ]; then
        $SEL/test/dev-bin/clang-diff-test --types $d
        if [ $? = "0" ]; then   
            echo $d;
        fi
    fi
done

       
