#!/bin/bash
S=cpp
i=1
mkdir -p results/
for d in `cat d`; do
  echo $d
  B=results/$i
  let i=i+1  
  mkdir -p $B
  echo $d > $B/source
  cp $d $B/f.$S
  (cd $B; FILE=f.$S creduce ../../check-interesting f.$S)
done