#include "GTDockerConfig.h"
#include "GTSELConfig.h"

FROM __GTD__MAKE_FROM(synthesis/cl)

RUN apt_deps=__GTD__SEL_APT_DEPS && \
    apt-get -y update && apt-get -y install ${apt_deps}

RUN mkdir -p __GTD__PATH_SEL_HOME && \
    git clone git@git.grammatech.com:synthesis/sel.git __GTD__PATH_SEL_HOME && \
    cd __GTD__PATH_SEL_HOME && \
    make se-test

WORKDIR __GTD__PATH_GT_ROOT

CMD /bin/bash
